version: '3'

tasks:
  build-cli:
    cmds:
      - go build -o dist/cli/main ./cmd/cli

  build-server:
    cmds:
      - go build -o dist/server/main ./cmd/server

  build-wasm:
    cmds:
      - cp "$(go env GOROOT)/lib/wasm/wasm_exec.js" ./web/public/
      - GOOS=js GOARCH=wasm go build -o web/public/led-gen.wasm ./cmd/wasm

  build-web:
    deps: [build-wasm]
    cmds:
      - cd web && pnpm run build

  build-all:
    deps: [build-cli, build-server, build-wasm]

  dev-web:
    cmds:
      - cd web && pnpm run dev

  default:
    cmds:
      - go tool task --list-all